enum ErrorCode {
    IS_NOT_A_STRING_ERROR = "IS_NOT_A_STRING_ERROR",
    IS_NOT_A_NUMBER_ERROR = "IS_NOT_A_NUMBER_ERROR",
    IS_REQUIRED_ERROR = "IS_REQUIRED_ERROR",
    NOT_PASSED_TEST_ERROR = "NOT_PASSED_TEST_ERROR",
    TO_SMALL_ERROR = "TO_SMALL_ERROR",
    TO_BIG_ERROR = "TO_BIG_ERROR",
    TO_SHORT_ERROR = "TO_SHORT_ERROR",
    TO_LONG_ERROR = "TO_LONG_ERROR",
    IS_NOT_AN_ARRAY_ERROR = "IS_NOT_AN_ARRAY_ERROR",
    IS_NOT_BOOLEAN = "IS_NOT_BOOLEAN",
    NOT_MATCH_ERROR = "NOT_MATCH_ERROR"
}

export {
    ErrorCode
}